### DISCUSSION TITLE
Example on Rendering PDFs using other providers like jsPDF

### DISCUSSION THREAD

**Discussion by s-hamdananwar** [OnedocLabs/react-print-pdf#10] [Q&A]
Hi Team, really excited to use this product! I was wondering if you guys have any examples on using other providers like jsPDF to render the HTML into PDF without using OneDocLabs. Thanks!

**Comment by AugusteLef** [comment]
Hey!

Just a heads-up that certain components of the react-print-pdf library might not render correctly in PDF with alternative solutions like Puppeteer for example—this especially applies to footers, headers, tailwind components, and other complex elements. That's why we recommend using Onedoc, which now offers 500 free documents per month, covering most personal use cases. 

If you prefer a different renderer, I don't have any code to share right now but will check on Discord and update you ASAP. Meanwhile, if anyone has a successful example, please feel free to share it here and we could include it in the react-print-pdf documentation (which you can also contribute to directly on the repo)!

**Reply by nktnet1** [reply]
Hi @AugusteLef,

Do you have any updates on this? Thank you ~

**Reply by Titou325** [reply]
Hi @nktnet1,

There is no plan to support other renderers as Fileforge is sunsetting, however we welcome contributions.

Components such as Tailwind, Markdown, LaTeX, CSS and Font will work with other HTML to PDF renderers usually. Layout elements should work with PrinceXML and DocRaptor, with slight modifications.

Thanks,
Titouan

**Comment by nktnet1** [comment]
A basic example of returning a PDF from compiled HTML (using [playwright](https://playwright.dev/)):

```ts
import playwright from 'playwright';

export const generatePDF = async (html: string) => {
  const browser = await playwright.chromium.launch();
  const page = await browser.newPage();
  await page.setContent(html);
  const res = await page.pdf({
    // format: 'A4',
    // scale: 1,
    // printBackground: true,
    // margin: {
    //   top: '0px',
    //   bottom: '0px',
    //   left: '0px',
    //   right: '0px',
    // },
    // pageRanges: '1',
  });
  await browser.close();
  return res;
};
```

and, for example, in a NextJS API route:

```ts
import { compile } from '@fileforge/react-print';

export const GET = async (req) => {

  const html = await compile(YourDocumentComponent({ yourProps }));
  const pdf = await generatePDF(html);

  return new Response(pdf, {
    headers: {
      'Content-Type': 'application/pdf',
    },
  });
};
```

Note
- you won't be able to deploy playwright to Vercel out of the box
- you may want to keep the playwright chromium browser opened and re-use it, instead of launching a new one each time

**Reply by nktnet1** [reply]
For anyone else stumbling here, I suggest trying out gotenberg:
- https://github.com/gotenberg/gotenberg

It is self-hostable as a Docker Image. For example, here is the docker-compose I use on Dokploy:
```yaml
services:
  gotenberg:
    image: gotenberg/gotenberg:latest
    environment:
      # NOTE: requires the --api-enable-basic-auth option in "command"
      #       make sure to also change the credentials in Dokploy environment
      GOTENBERG_API_BASIC_AUTH_USERNAME: ${GOTENBERG_API_BASIC_AUTH_USERNAME}
      GOTENBERG_API_BASIC_AUTH_PASSWORD: ${GOTENBERG_API_BASIC_AUTH_PASSWORD}
    command: [
      "gotenberg",
      # See the full list of options at https://gotenberg.dev/docs/configuration
      
      # Examples:
      "--api-enable-basic-auth",
      "--api-timeout=60s",
      "--chromium-auto-start"
    ]
    restart: unless-stopped
    deploy:
      replicas: 3
```

A basic code snippet, assuming you've generated your `html` string using the the `compile` function from `@fileforge/react-print` as shown in my example in the original post:
```ts
const GOTENBERG_BASE_URL = process.env.GOTENBERG_BASE_URL!;
const GOTENBERG_API_BASIC_AUTH_USERNAME = process.env.GOTENBERG_API_BASIC_AUTH_USERNAME!;
const GOTENBERG_API_BASIC_AUTH_PASSWORD = process.env.GOTENBERG_API_BASIC_AUTH_PASSWORD!;

export const generatePDF = async (html: string): Promise<Buffer | null> => {
  const formData = new FormData();
  formData.append('files', new Blob([html], { type: 'text/html' }), 'index.html');
  formData.append('preferCssPageSize', 'true');
  formData.append('generateDocumentOutline', 'true');

  try {
    const response = await fetch(`${GOTENBERG_BASE_URL}/forms/chromium/convert/html`, {
      method: 'POST',
      headers: {
        Authorization: `Basic ${Buffer.from(
          `${GOTENBERG_API_BASIC_AUTH_USERNAME}:${GOTENBERG_API_BASIC_AUTH_PASSWORD}`,
        ).toString('base64')}`,
      },
      signal: AbortSignal.timeout(60_000),
      body: formData,
    });

    if (!response.ok) {
      throw new Error(
        `${response.status} Failed to generate PDF. Status: ${response.status}, Message: ${response.statusText}`,
      );
    }
    return Buffer.from(await response.arrayBuffer());
  } catch (error: unknown) {
    console.error('Failed to generate PDF document with Gotenberg:', error);
    return null;
  }
};
```
